
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author willi
 */
public class UpdateAvaliacoes extends javax.swing.JDialog {

    CRUD crud = new CRUD();
    boolean up = false;
    AvaliacoesBanco a;
    /**
     * Creates new form UpdateProduto
     */
    public UpdateAvaliacoes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public UpdateAvaliacoes(java.awt.Frame parent, boolean modal, AvaliacoesBanco a) {
        super(parent, modal);
        initComponents();
        this.a = new AvaliacoesBanco(a.getId(), a.getSubmissao(), a.getAvaliador(), a.getDataParecer(), a.getArquivoProjeto(), a.getStatus());
        
        this.jTextFieldSubmissao.setText(String.valueOf(a.getSubmissao()));
        this.jTextFieldAvaliador.setText(String.valueOf(a.getAvaliador()));
        this.jTextFieldDataParecer.setText(String.valueOf(a.getDataParecer()));
        this.jTextFieldArquivoProjeto.setText(String.valueOf(a.getArquivoProjeto()));
        this.jTextFieldStatus.setText(String.valueOf(a.getStatus()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSubmissao = new javax.swing.JTextField();
        jTextFieldAvaliador = new javax.swing.JTextField();
        jTextFieldDataParecer = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter cpf= new javax.swing.text.MaskFormatter("####-##-##");
            jTextFieldDataParecer = new javax.swing.JFormattedTextField(cpf);
        }
        catch (Exception e){
        }
        jTextFieldArquivoProjeto = new javax.swing.JTextField();
        jTextFieldStatus = new javax.swing.JTextField();
        jToggleButtonSalvar = new javax.swing.JToggleButton();
        jToggleButtonSair = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Submissão:");

        jLabel2.setText("Avaliador:");

        jLabel3.setText("Data do Parecer:");

        jLabel4.setText("Arquivo do Projeto:");

        jLabel5.setText("Status:");

        jTextFieldSubmissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSubmissaoFocusLost(evt);
            }
        });

        jTextFieldAvaliador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAvaliadorFocusLost(evt);
            }
        });
        jTextFieldAvaliador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAvaliadorActionPerformed(evt);
            }
        });

        jTextFieldArquivoProjeto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldArquivoProjetoFocusLost(evt);
            }
        });

        jTextFieldStatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldStatusFocusLost(evt);
            }
        });

        jToggleButtonSalvar.setText("Salvar");
        jToggleButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSalvarActionPerformed(evt);
            }
        });

        jToggleButtonSair.setText("Sair");
        jToggleButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSairActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Editar Avaliações");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                            .addComponent(jTextFieldSubmissao)
                            .addComponent(jTextFieldAvaliador)
                            .addComponent(jTextFieldDataParecer)
                            .addComponent(jTextFieldArquivoProjeto)
                            .addComponent(jTextFieldStatus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel6)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jTextFieldSubmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jTextFieldAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jTextFieldDataParecer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldArquivoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jToggleButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jToggleButtonSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jToggleButtonSairActionPerformed

    private void jToggleButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSalvarActionPerformed
        if (jTFsNotEmpty()) {
            String submissao = jTextFieldSubmissao.getText();
            String avaliador = jTextFieldAvaliador.getText();
            String dataParecer = jTextFieldDataParecer.getText();
            String arquivoProjeto = jTextFieldArquivoProjeto.getText();
            String status = jTextFieldStatus.getText();

            a.setSubmissao(submissao);
            a.setAvaliador(avaliador);
            a.setDataParecer(dataParecer);
            a.setArquivoProjeto(arquivoProjeto);
            a.setStatus(status);

            if (crud.updateAvaliacoes(a)) {
                JOptionPane.showMessageDialog(null, "Avaliação Editada!");
                this.up = true;
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Avaliação Não Editada!\nTente novamente");
            }      
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos!");
        }
    }//GEN-LAST:event_jToggleButtonSalvarActionPerformed

    private void jTextFieldAvaliadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAvaliadorActionPerformed
        JTextField campo = (JTextField) evt.getSource();
        int posicaoCursor = campo.getCaretPosition();
        campo.setText(campo.getText().toUpperCase());
        if (posicaoCursor != campo.getCaretPosition()) {
            campo.setCaretPosition(posicaoCursor);
        }
    }//GEN-LAST:event_jTextFieldAvaliadorActionPerformed

    private void jTextFieldSubmissaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSubmissaoFocusLost
        JTextField campo = (JTextField) evt.getSource();
        int posicaoCursor = campo.getCaretPosition();
        campo.setText(campo.getText().toUpperCase());
        if (posicaoCursor != campo.getCaretPosition()) {
            campo.setCaretPosition(posicaoCursor);
        }
    }//GEN-LAST:event_jTextFieldSubmissaoFocusLost

    private void jTextFieldAvaliadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAvaliadorFocusLost
        JTextField campo = (JTextField) evt.getSource();
        int posicaoCursor = campo.getCaretPosition();
        campo.setText(campo.getText().toUpperCase());
        if (posicaoCursor != campo.getCaretPosition()) {
            campo.setCaretPosition(posicaoCursor);
        }
    }//GEN-LAST:event_jTextFieldAvaliadorFocusLost

    private void jTextFieldArquivoProjetoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldArquivoProjetoFocusLost
        JTextField campo = (JTextField) evt.getSource();
        int posicaoCursor = campo.getCaretPosition();
        campo.setText(campo.getText().toUpperCase());
        if (posicaoCursor != campo.getCaretPosition()) {
            campo.setCaretPosition(posicaoCursor);
        }
    }//GEN-LAST:event_jTextFieldArquivoProjetoFocusLost

    private void jTextFieldStatusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldStatusFocusLost
        JTextField campo = (JTextField) evt.getSource();
        int posicaoCursor = campo.getCaretPosition();
        campo.setText(campo.getText().toUpperCase());
        if (posicaoCursor != campo.getCaretPosition()) {
            campo.setCaretPosition(posicaoCursor);
        }
    }//GEN-LAST:event_jTextFieldStatusFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAvaliacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAvaliacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAvaliacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAvaliacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateAvaliacoes dialog = new UpdateAvaliacoes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private boolean jTFsNotEmpty() {
        return !("".equals(jTextFieldSubmissao.getText()) &&
                "".equals(jTextFieldAvaliador.getText()) &&
                "".equals(jTextFieldDataParecer.getText()) &&
                "".equals(jTextFieldArquivoProjeto.getText()) &&
                "".equals(jTextFieldStatus.getText()));
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldArquivoProjeto;
    private javax.swing.JTextField jTextFieldAvaliador;
    private javax.swing.JTextField jTextFieldDataParecer;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldSubmissao;
    private javax.swing.JToggleButton jToggleButtonSair;
    private javax.swing.JToggleButton jToggleButtonSalvar;
    // End of variables declaration//GEN-END:variables
}